# Generated by Django 4.0.4 on 2022-06-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hammer', '0002_alter_contacto_telefono_alter_empleado_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleador',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
